services:
  db:
    image: postgres:17
    container_name: postgres_local
    restart: unless-stopped
    ports:
      - "5432:5432"
    volumes:
      - ./.local_db/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=hrvatsk_ai

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin_local
    restart: unless-stopped
    ports:
      - "5050:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    volumes:
      - ./.local_db/pgadmin:/var/lib/pgadmin
    depends_on:
      db:
        condition: service_started
