"""
Pydantic schemas for Lesson Planner agent output.

These models define the structured output format for lesson plans generated by the LLM.
Use LessonPlan.model_json_schema() to generate JSON schema for prompts.
"""

from typing import Literal

from pydantic import BaseModel, Field


class Objective(BaseModel):
    """A single learning objective for the session."""

    id: str
    description: str
    priority: int = Field(ge=1, le=3)
    measurable_outcome: str


class VocabularyTarget(BaseModel):
    """A vocabulary word to teach in the session."""

    word: str
    translation: str
    part_of_speech: str
    priority: int = Field(ge=1, le=3)
    gender: str | None = None
    case_focus: str | None = None
    usage_context: str | None = None


class GrammarFocus(BaseModel):
    """Grammar concept to focus on during the session."""

    concept: str
    concept_slug: str
    level: Literal["introduce", "practice", "reinforce", "master"]
    key_rules: list[str]
    examples: list[str]
    common_mistakes_to_watch: list[str] | None = None


class ConversationScenario(BaseModel):
    """Role-play scenario for the lesson."""

    setting: str
    student_role: str
    tutor_role: str
    key_phrases: list[str]
    situation_description: str | None = None
    conversation_starters: list[str] | None = None


class AdaptationTriggers(BaseModel):
    """Conditions for adapting the lesson difficulty."""

    simplify_if: list[str] | None = None
    advance_if: list[str] | None = None


class LessonPlan(BaseModel):
    """Complete lesson plan generated by the Lesson Planner agent."""

    session_duration_minutes: int = Field(gt=0)
    level: Literal["A1", "A2", "B1", "B2", "C1", "C2"]
    objectives: list[Objective] = Field(min_length=2, max_length=3)
    vocabulary_targets: list[VocabularyTarget]
    grammar_focus: GrammarFocus
    conversation_scenario: ConversationScenario
    success_criteria: list[str] = Field(min_length=2, max_length=4)
    adaptation_triggers: AdaptationTriggers | None = None
